# Generated by Django 4.0.6 on 2022-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
