# Generated by Django 4.0.6 on 2022-07-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_ticket_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.ticketresponse'),
        ),
    ]
