# Generated by Django 4.0.6 on 2022-07-26 17:51

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='videos',
        ),
        migrations.AddField(
            model_name='tag',
            name='blood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='drug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='violence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ForeignKey(default=videos.models.Tag.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='videos.tag'),
        ),
    ]
