# Generated by Django 4.0.6 on 2022-07-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_tag_title_remove_tag_videos_tag_blood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tag'),
        ),
    ]
